### PR TITLE
support intl.get(key) type check

### PR DESCRIPTION
**Pull request by hardfist**
Change-Id: I66f70281e5f074cc83204e4aff64cf05c57265a2

### CODE REVIEW

**Comment by jhaenchen** [comment]
@cwtuan Can we merge? i love this <3

**Comment by jhaenchen** [comment]
I still love this and would still love to see it merged!

**Comment by cwtuan** [comment]
This PR makes existing project shows error if they doesn't have the [definition](https://github.com/alibaba/react-intl-universal/blob/da5a115ef4461ed66e5658c34437fb02275461bf/examples/typescript-example/typings/module.ts) file. 

This also force users to enable the ts type checking even if they don't want this feature.

**Comment by hardfist** [comment]
Yes, It's a breaking change, and I think It's impossible to implement key check without introducing breaking change, and the fixing is easy for old project.
for js project there is not problem,
for ts project just adding this declaration.
```
declare module 'react-intl-universal' {
  export interface Message extends Record<string, string> {}
}
```

**Comment by hardfist** [comment]
@cwtuan Yes, we could disable this feature by default by using  generic parameter default 
```
 /**
     * Get the formatted message by key
     * @param {string} key The string representing key in locale data file
     * @returns {string} message
     */
    export function get<T = Key>(key:T): string;
```
in which key type check is disabled unless you pass type to generic

But I thinks it's kind of annoying to pass type every time

**Comment by jhaenchen** [comment]
Maybe we could add another .get function signature or get function? Like getSafely?

**Comment by cwtuan** [comment]
@jhaenchen 
Another signature may make user confused.

**Pull request closed without merging**
