### PR TITLE
Drop querystring dependency

### PR DESCRIPTION
**Pull request by Chevindu**
# Pull Request Template

## Description

This change removes the dependency on [`querystring`](https://www.npmjs.com/package/querystring), which clears the following warning logged by NPM when installing `react-intl-universal`.

```
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Using the existing test case: "Get locale from URL"

### CODE REVIEW

**Comment by Chevindu** [comment]
Hi @cwtuan , please have a look at this if the time permits. I'm happy to do any tweaks if needed. Thank you.

**Comment by cwtuan** [comment]
@Chevindu please see the comment above

**Comment by Chevindu** [comment]
> @Chevindu please see the comment above

Which one please? I only see the comment by CLAssistant which says "All committers have signed the CLA". I'm sorry if I misunderstood.

**Comment by cwtuan** [comment]
image

**Comment by Chevindu** [comment]
> image

Thanks for the screenshot. I am unable to see your comment in my PR. Might be because the comment is still in Pending state.

I edited my PR according to your comment. However, `jest`, `jest-cli` and `babel-jest` [had to be updated to v22](https://jestjs.io/blog/2017/12/18/jest-22#good-bye-node-4--welcome-jsdom-11) for jsdom to have access to URLSearchParams global.

**Review by cwtuan — APPROVED** [review]

**Comment by cwtuan** [comment]
Thanks for your awesome work! This PR is done. 
Version: `react-intl-universal@2.11.1`

**Pull request merged**
