### PR TITLE
Add a new option `enableWarning`

### PR DESCRIPTION
**Pull request by zry656565**
- Add a new option `enableWarning` to determine if showing warning messages.
- It's helpful to disable warnings in prod environment.

### CODE REVIEW

**Comment by spherop** [comment]
This is a must have for serious production use in my book. Is there a chance of merging?

**Comment by alexeyMohnatkin** [comment]
It's better to pass callback function instead of flag
```
intl.init({ 
  locales, 
  currentLocale,
  notDefinedHandler: R.identity,
});
```
#47

**Comment by cwtuan** [comment]
I prefer the solution from @alexeyMohnatkin. Please see the comment in the PR. Thanks.

**Comment by zry656565** [comment]
@cwtuan So why not just accpet Alexey's solution? It's fine to me. What I want is to solve the problem, no matter how.

Btw, I think the variable name, `notDefinedHandler`, may not be proper for this line (https://github.com/alibaba/react-intl-universal/pull/47/files#diff-1fdf421c05c1140f6d71444ea2b27638R83)

**Comment by cwtuan** [comment]
@zry656565 any suggestion for the variable name?

**Comment by zry656565** [comment]
@cwtuan Maybe a more general name like `warningLogger` or `warningHandler`? idk, it's up to you.

**Comment by alexeyMohnatkin** [comment]
I agree that `notDefinedHandler` is not the best name. What if I add callback for each warning to handle them separately?
```
{
  ...
  msgNotFound: console.warn,
  msgFormatFailed: console.warn,
  langNotSupported: console.warn,
}
```

**Comment by alexeyMohnatkin** [comment]
@zry65656 I think it's bad practice to disable these warnings. You may never know that something's wrong

**Comment by cwtuan** [comment]
Fixed v1.11.1.
https://github.com/alibaba/react-intl-universal/releases/tag/1.11.1

**Pull request closed without merging**
